#!/bin/bash

getprop() { #A function called getprop has been created to run when executed.
    fname=$1 #the file name is stored when entered after the first command.
    fsize=$(du -b $f) #The file size is obtained from the system information on disk usage, in bytes, of the file.
    kb=$($fsize*1024 | bc) #The file size in bytes uses a bash calculator to convert the size to kilobytes.
    wcnt='grep wc-1' fname #A word count is generated by using grep to search the number of words in the file entered at the command.
    mod=$(stat -f %Sm -t "%d-%m-%Y %H:%M:%S") #The status of the file modification time is extracted from the system storage manager and output format isd-mm-yy hh-mm-ss.
    echo -e "The file $1 contains $wcnt words and is $kb in size and was last modified $mod" #The results for the file size in kilobytes, word count, and modification date and time - 
}                                                                                            #- entered at the command line are echoed.
 #The function is closed off.

read -p "Enter the file name to check: " fname #When the script is run, it propmts the user to enter a file name.
 getprop $fname #The function is executed to run and echo the response.